### Import important libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Generate Datapoints:

In [2]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [0]])

In [3]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
Y

array([[0],
       [1],
       [1],
       [0]])

### Building NN Model

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

2025-07-02 11:16:00.420275: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-02 11:16:00.835310: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
model = Sequential()

2025-07-02 11:16:05.409316: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-07-02 11:16:05.593656: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-07-02 11:16:05.593741: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-07-02 11:16:05.600940: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-07-02 11:16:05.602475: I tensorflow/compile

In [7]:
model.add(Dense(4, "relu"))

In [8]:
model.add(Dense(1, "sigmoid"))

#### Compilation: Preparing the NN for training: how the learning is happening, what to minimise and which performance metric to track

In [9]:
model.compile(Adam(0.1), "mse", metrics=["accuracy"])

#### Training the model

In [11]:
model.fit(X, Y, epochs=500, batch_size=8192)

Epoch 1/500
1/1 [==============================] - 0s 18ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 13ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 3/500
1/1 [==============================] - 0s 19ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 4/500
1/1 [==============================] - 0s 13ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 5/500
1/1 [==============================] - 0s 16ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 6/500
1/1 [==============================] - 0s 15ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 7/500
1/1 [==============================] - 0s 12ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 8/500
1/1 [==============================] - 0s 15ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 13ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 10/500
1/1 [==============================] - 0s 18ms/step - loss: 0.1667 - accuracy: 0.7500
Epoch 11/500
1/1 [=

#### Testing the model

In [12]:
predictions = model.predict(X)

1/1 [==============================] - 0s 65ms/step


In [13]:
predictions

array([[0.6666645 ],
       [0.6666645 ],
       [0.6666645 ],
       [0.00120719]], dtype=float32)

In [14]:
predictions = np.round(predictions)

In [15]:
predictions

array([[1.],
       [1.],
       [1.],
       [0.]], dtype=float32)