In [1]:
import numpy as np

Q1. Create a null vector of size 10 but the fifth value is 1.

In [2]:
array = np.zeros(10)
array[4] = 1
print("Resultant vector is:", array)

Resultant vector is: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Q2. Create a vector with values ranging from 10 to 49

In [3]:
print("Vector from 10 to 49:", np.arange(10, 50))

Vector from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Q3. Reverse a vector (first element becomes last) 

In [4]:
array = np.array(eval(input("Enter a vector: ")))
print("The reverse of", array, "is:", array[::-1])

Enter a vector:  1, 2, 3, 4, 5


The reverse of [1 2 3 4 5] is: [5 4 3 2 1]


Q4. Create a 3x3 matrix with values ranging from 0 to 8  
`hint: reshape`

In [5]:
print("Resultant Matrix is:", np.arange(9).reshape(3, 3), sep='\n')

Resultant Matrix is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Q5. Find indices of non-zero elements from [1,2,0,0,4,0]  
`hint: np.nonzero`

In [6]:
print("Indices of non-zero elements are:", *np.nonzero([1,2,0,0,4,0]))

Indices of non-zero elements are: [0 1 4]


Q6. Create a 3x3x3 array with random values  
`hint: np.random.random`

In [7]:
print("3x3x3 random array is:", np.random.random(3 * 3 * 3).reshape(3, 3, 3), sep='\n')

3x3x3 random array is:
[[[0.60933484 0.52582766 0.62589253]
  [0.17002817 0.51103469 0.58131022]
  [0.0775492  0.61766152 0.43757921]]

 [[0.70383248 0.91871757 0.61580699]
  [0.71714727 0.67080727 0.98180537]
  [0.30607442 0.93248703 0.72803446]]

 [[0.21195715 0.15394802 0.11942443]
  [0.32322313 0.00397616 0.41945713]
  [0.2464304  0.46273515 0.30150582]]]


Q7. Create a 10x10 array with random values and find the minimum and maximum values   
`hint: min, max`

In [8]:
array = np.random.random(10 * 10).reshape(10, 10)
print("The randon 10x10 array is:", array, sep='\n')
print("Min element in array is:", np.min(array))
print("Max element in array is:", np.max(array))

The randon 10x10 array is:
[[0.54122237 0.0015641  0.71885468 0.52978421 0.43366877 0.24985095
  0.4912349  0.33358858 0.22310592 0.41529194]
 [0.71060214 0.98911824 0.26512873 0.29249409 0.04720497 0.05232952
  0.91673445 0.35865153 0.90821398 0.60832822]
 [0.15521744 0.74018573 0.94080759 0.62437817 0.99378903 0.5727482
  0.13251614 0.72724194 0.48168816 0.92371513]
 [0.38113307 0.10086444 0.11028278 0.65285903 0.25080285 0.50846497
  0.26406133 0.80107028 0.20261918 0.54065655]
 [0.94742538 0.35552703 0.58355349 0.96043833 0.94479386 0.82633547
  0.16786722 0.90981242 0.40493989 0.01569565]
 [0.08072815 0.38446545 0.24942361 0.02657823 0.95444883 0.89196379
  0.96149114 0.43598533 0.58873088 0.62277719]
 [0.77561912 0.56854045 0.89665915 0.96370564 0.98232116 0.52334047
  0.1661667  0.86505395 0.2133842  0.49301896]
 [0.57502499 0.58289874 0.45970327 0.40703404 0.70961382 0.49093524
  0.5920924  0.60339127 0.7323137  0.37356817]
 [0.91674439 0.6716242  0.79461978 0.0389574  0.191993

Q8. Create a random vector of size 30 and find the mean value  
`hint: mean` 

In [9]:
array = np.random.random(30)
print("The random vector of size 30 is:", array)
print("The mean of the vector is:", np.mean(array))

The random vector of size 30 is: [0.62977485 0.65716982 0.1543225  0.1915184  0.41911982 0.7985011
 0.567872   0.33223942 0.27025378 0.02790098 0.54618772 0.49281866
 0.15704597 0.38918319 0.72566443 0.10018162 0.09867815 0.86047085
 0.36050015 0.7269926  0.87193128 0.82933122 0.8447089  0.96916825
 0.29754897 0.64715294 0.89270192 0.65497564 0.20575318 0.07241224]
The mean of the vector is: 0.4930693526562002


Q9. Create a 2d array with 1 on the border and 0 inside  
`hint: array[1:-1, 1:-1]`

In [10]:
row, column = eval(input("Enter the dimension of the matrix"))
array = np.ones(row * column).reshape(row, column)
array[1:-1, 1:-1] = 0
print(array)

Enter the dimension of the matrix 5, 4


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Q10. Normalize a 5x5 random matrix   
`hint: (x -mean)/std` 

In [11]:
array = np.random.random(5 * 5).reshape(5, 5)
print("Normalized matrix: ", (array - np.mean(array)) / np.std(array), sep='\n')

Normalized matrix: 
[[ 0.19401749  0.34895444  1.40562861 -1.25499841 -1.21323928]
 [ 0.4814916   0.01167786  1.29802223  0.80706126  1.78302316]
 [-0.94289924 -1.1330177   0.2335272  -0.53132293 -0.30453408]
 [-1.33193649  0.94861026 -0.80448164  1.86072318 -0.4707495 ]
 [-0.64386826 -0.19525568 -0.8280496  -1.14081077  1.42242629]]


Q11. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [12]:
array1 = np.random.random(5 * 3).reshape(5, 3)
array2 = np.random.random(3 * 2).reshape(3, 2)
print("Matrix Multiplication of", array1, "and", array2, "is:", array1 @ array2, sep='\n')

Matrix Multiplication of
[[0.33724357 0.48559591 0.33716479]
 [0.62583208 0.73605167 0.03662362]
 [0.17234402 0.1649725  0.93711043]
 [0.44456836 0.69744029 0.38521851]
 [0.88255405 0.23339189 0.7330649 ]]
and
[[0.95819795 0.65118561]
 [0.10793389 0.4034859 ]
 [0.85835824 0.89161156]]
is:
[[0.66496653 0.71615928]
 [0.71055212 0.73717336]
 [0.98732227 1.01433052]
 [0.83191742 0.91436912]
 [1.50008468 1.32248598]]


Q12. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [13]:
array = np.array(eval(input("Enter a array of size 10:")))
array[(array >= 3) & (array <= 8)] *= -1
print("Array after negating elemnts between 3 and 8 are:", array)

Enter a array of size 10: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10


Array after negating elemnts between 3 and 8 are: [ 1  2 -3 -4 -5 -6 -7 -8  9 10]


Q13.  Find the eigenvalues and eigenvectors of a square matrix.  
`hint: np.linalg.eig`

In [14]:
array = np.array(eval(input("Enter a square matrix:")))
eigen_values, eigen_vectors = np.linalg.eig(array)
print("The square matrix is:", array, sep='\n')
print("The eigen values are:", eigen_values)
print("The eigen vectors are:", eigen_vectors, sep='\n')

Enter a square matrix: [[1, 2], [3, 4]]


The square matrix is:
[[1 2]
 [3 4]]
The eigen values are: [-0.37228132  5.37228132]
The eigen vectors are:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Q14. Find the inverse of a square matrix.  
`hint: np.linalg.inv`

In [15]:
array = np.array(eval(input("Enter a square matrix:")))
print("Inverse of", array, "is:", np.linalg.inv(array), sep='\n')

Enter a square matrix: [[1, 2], [3, 4]]


Inverse of
[[1 2]
 [3 4]]
is:
[[-2.   1. ]
 [ 1.5 -0.5]]
