In [1]:
array = [1, 2, 3, 4, 5]
["a", "b", "c", 1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [2]:
import numpy as np

In [3]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmi

In [4]:
list1 = [1, 2, 3, 4, 5]
array1 = np.array(list1)

In [5]:
type(array1)

numpy.ndarray

In [6]:
type(list1)

list

In [7]:
import time

size = 1000000
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(l1, l2)]
print("list time:", time.time() - start)

a1 = np.arange(size)
a2 = np.arange(size)
start = time.time()
result = a1 + a2
print("numpy time:", time.time() - start)

list time: 0.07428216934204102
numpy time: 0.012038707733154297


In [8]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


np.zeroes()

In [9]:
zero = np.zeros((2, 3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
zero = np.zeros((20, 10))
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
one = np.ones((5, 6))
one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
range_array = np.arange(10, 150, 2)  # start stop step
range_array

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110, 112,
       114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138,
       140, 142, 144, 146, 148])

In [13]:
linspace = np.linspace(10, 150, 20)
linspace

array([ 10.        ,  17.36842105,  24.73684211,  32.10526316,
        39.47368421,  46.84210526,  54.21052632,  61.57894737,
        68.94736842,  76.31578947,  83.68421053,  91.05263158,
        98.42105263, 105.78947368, 113.15789474, 120.52631579,
       127.89473684, 135.26315789, 142.63157895, 150.        ])

In [14]:
linspace = np.linspace(10, 150, 2000)
linspace

array([ 10.        ,  10.07003502,  10.14007004, ..., 149.85992996,
       149.92996498, 150.        ])

In [15]:
linspace = np.linspace(0, 1, 10)
linspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
linspace = np.linspace(0, 1, 15)
linspace

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [17]:
0.07142857 - 0.14285714

-0.07142857

In [18]:
0.14285714 - 0.21428571

-0.07142857

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a.shape

(2, 3)

In [21]:
a.shape[0]

2

In [22]:
a.shape[1]

3

In [23]:
linspace.shape

(15,)

In [24]:
a.ndim

2

In [25]:
linspace.ndim

1

In [26]:
a.dtype

dtype('int64')

In [27]:
linspace.dtype

dtype('float64')

In [28]:
linspace.size

15

In [29]:
a.size

6

In [30]:
b = np.array([10, 20, 30, 40, 50, 60])
b
print("self is b:", b)

self is b: [10 20 30 40 50 60]


In [31]:
b[0]

np.int64(10)

In [32]:
b[-1]

np.int64(60)

In [33]:
b[1:4]

array([20, 30, 40])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a[0, 0]

np.int64(1)

In [36]:
a[0, 2]

np.int64(3)

In [37]:
a[:, 1]  # all rows of column 1

array([2, 5])

In [38]:
a[1, :]  # all column of row 1

array([4, 5, 6])

In [39]:
c = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

In [40]:
c.shape

(2, 2, 3)

In [41]:
c[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
c[0, 1, 1]

np.int64(5)

In [43]:
c[0, 1, 0:2]

array([4, 5])

In [44]:
linspace

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [45]:
linspace[::-1]

array([1.        , 0.92857143, 0.85714286, 0.78571429, 0.71428571,
       0.64285714, 0.57142857, 0.5       , 0.42857143, 0.35714286,
       0.28571429, 0.21428571, 0.14285714, 0.07142857, 0.        ])

In [46]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [47]:
a + b

array([ 7,  9, 11, 13, 15])

In [48]:
a - b

array([-5, -5, -5, -5, -5])

In [49]:
a * b

array([ 6, 14, 24, 36, 50])

In [50]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [51]:
a ** b

array([      1,     128,    6561,  262144, 9765625])

In [52]:
numbers = np.array([[1, 2, 3], [4, 5, 6]])
numbers

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
numbers.sum()

np.int64(21)

In [54]:
numbers[1].sum()

np.int64(15)

In [55]:
numbers.mean()

np.float64(3.5)

In [56]:
numbers.min()

np.int64(1)

In [57]:
numbers[1].min()

np.int64(4)

In [58]:
numbers.max()

np.int64(6)

In [59]:
numbers[0].max()

np.int64(3)

In [60]:
numbers = np.array([[1, 2, 3], [4, 5, 6]])
numbers

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
numbers.sum(axis=0)  # column-wise sum

array([5, 7, 9])

In [62]:
numbers.sum(axis=1)  # row-wise sum

array([ 6, 15])

physics, chemistry, maths<br>
min, max, avg, sum of marks of a student, topper in entire class and lowest in entire class and also subject wise

In [63]:
grades = np.array([[85, 90, 78],
                   [88, 92, 80],
                   [75, 85, 89]])

In [64]:
print("Min marks in Physics:", grades[0].min())
print("Min marks in Chemistry:", grades[1].min())
print("Min marks in Maths:", grades[2].min())
print("Min marks in entire class:", grades.min())

Min marks in Physics: 78
Min marks in Chemistry: 80
Min marks in Maths: 75
Min marks in entire class: 75


In [65]:
print("Max marks in Physics:", grades[0].max())
print("Max marks in Chemistry:", grades[1].max())
print("Max marks in Maths:", grades[2].max())
print("Max marks in entire class:", grades.max())

Max marks in Physics: 90
Max marks in Chemistry: 92
Max marks in Maths: 89
Max marks in entire class: 92


In [66]:
print("Avg marks in Physics:", grades[0].mean())
print("Avg marks in Chemistry:", grades[1].mean())
print("Avg marks in Maths:", grades[2].mean())
print("Avg marks in entire class:", grades.mean())

Avg marks in Physics: 84.33333333333333
Avg marks in Chemistry: 86.66666666666667
Avg marks in Maths: 83.0
Avg marks in entire class: 84.66666666666667


In [67]:
print("Sum marks in Physics:", grades[0].sum())
print("Sum marks in Chemistry:", grades[1].sum())
print("Sum marks in Maths:", grades[2].sum())
print("Sum marks in entire class:", grades.sum())

Sum marks in Physics: 253
Sum marks in Chemistry: 260
Sum marks in Maths: 249
Sum marks in entire class: 762


In [68]:
grades_T = grades.T

In [69]:
print("Topper in Physics: Student", np.argmax(grades_T[0]))
print("Topper in Chemistry: Student", np.argmax(grades_T[1]))
print("Topper in Maths: Student", np.argmax(grades_T[2]))
print("Topper in entire class: Student", np.argmax(grades_T.sum(1)))

Topper in Physics: Student 1
Topper in Chemistry: Student 1
Topper in Maths: Student 2
Topper in entire class: Student 1


In [70]:
print("Lowest in Physics: Student", np.argmin(grades_T[0]))
print("Lowest in Chemistry: Student", np.argmin(grades_T[1]))
print("Lowest in Maths: Student", np.argmin(grades_T[2]))
print("Lowest in entire class: Student", np.argmin(grades_T.sum(1)))

Lowest in Physics: Student 2
Lowest in Chemistry: Student 2
Lowest in Maths: Student 0
Lowest in entire class: Student 2


In [71]:
a = np.array([1, 2, 3])

In [72]:
b = 10

In [73]:
a + b

array([11, 12, 13])

In [74]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
])  # Shape: (2, 3)

B = np.array([[1], [2]])  # Shape: (2, 1)

In [75]:
B.shape

(2, 1)

In [76]:
A.shape

(2, 3)

In [77]:
A + B

array([[11, 21, 31],
       [42, 52, 62]])

In [78]:
A * B

array([[ 10,  20,  30],
       [ 80, 100, 120]])

In [79]:
check = np.arange(1, 20, 2)
check

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [80]:
a = check.reshape((2, 5))
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [81]:
check = np.arange(1, 20, 2)
check.size

10

In [82]:
a = check.reshape((5, 2))
a

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [83]:
a = check.reshape((5, 2))
a

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [84]:
a = check.reshape((1, 5, 2))
a

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]]])

In [85]:
a.shape

(1, 5, 2)

In [86]:
a = check.reshape((1, 1, 5, 2))
a

array([[[[ 1,  3],
         [ 5,  7],
         [ 9, 11],
         [13, 15],
         [17, 19]]]])

In [87]:
a.shape

(1, 1, 5, 2)

Basic Statistics<br>
Normalization (scale to 0–1)<br>
Topper per Subject<br>
Add 5 grace marks to anyone scoring < 75 in any subject<br>
Compute overall class average after grace marks<br>
Identify students whose average is >= 90 and label them “Star Performers”<br>

In [88]:
students = np.array(["Alice", "Bob", "Carol", "David", "Eva"])
marks = np.array([
    [88, 92, 85],
    [75, 78, 80],
    [93, 88, 90],
    [70, 72, 68],
    [85, 90, 87]
])

In [89]:
print("Subject-wise average:", marks.mean(0))
print("Subject-wise max:", marks.max(0))
print("Subject-wise min:", marks.min(0))

print("Student-wise average:", marks.mean(1))

Subject-wise average: [82.2 84.  82. ]
Subject-wise max: [93 92 90]
Subject-wise min: [70 72 68]
Student-wise average: [88.33333333 77.66666667 90.33333333 70.         87.33333333]


In [90]:
(marks - marks.min()) / (marks.max() - marks.min())

array([[0.8 , 0.96, 0.68],
       [0.28, 0.4 , 0.48],
       [1.  , 0.8 , 0.88],
       [0.08, 0.16, 0.  ],
       [0.68, 0.88, 0.76]])

In [91]:
marks_T = marks.T

for i in range(len(marks_T)):
    print(f"Topper in Subject {i} is Student {np.argmax(marks_T[i])}")

Topper in Subject 0 is Student 2
Topper in Subject 1 is Student 0
Topper in Subject 2 is Student 2


In [92]:
graced = marks.copy()
graced[graced < 75] += 5
graced

array([[88, 92, 85],
       [75, 78, 80],
       [93, 88, 90],
       [75, 77, 73],
       [85, 90, 87]])

In [93]:
print("Overall class average after grace marks is:", graced.mean())

Overall class average after grace marks is: 83.73333333333333


In [94]:
for i, avg in enumerate(marks.mean(1)):
    if avg >= 90:
        print(f"Student {i} is a Star Performer")

Student 2 is a Star Performer
